spring.application.name=inventory

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=app
spring.datasource.password=apppass

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false