spring.application.name=inventory

spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true